# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# @NOTE @aharito это уже моё
posts_dir: /docs

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/evo-cms-logo.png"

title: AS-8X API Documentation
description: Как создать крутой блог на Evo CMS за полчаса (тут работы на полчаса).
baseurl: "/evo3blog-jtd" # repo folder
theme: just-the-docs

url: https://aharito.github.io

nav_external_links: false

aux_links_new_tab: true
aux_links:
  "mmCEsim on GitHub":
    - "//github.com/mmcesim"

# Back to top link
back_to_top: true
back_to_top_text: "↑ Back to top"

color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Կարևոր
    color: blue
  new:
    title: New
    color: green
  note:
    title: Նկատառում
    color: purple
  warning:
    title: Զգուշացում
    color: red

compress_html:
  ignore:
    envs: all